baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'FFXIV Gacha'

# Configure syntax highlight
[markup]
[markup.highlight]
style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html

[[module.mounts]]
source = "assets"
target = "assets"

SectionPagesMenu = "main"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Coffers"
url = "/coffer/"
weight = 2

[[menu.main]]
name = "Lockboxes"
url = "/lockbox/"
weight = 3

[[menu.main]]
name = "Ventures"
url = "/venture/"
weight = 4

[[menu.main]]
name = "Bnuuuy"
url = "/bunny/"
weight = 5

[[menu.main]]
name = "Deep Dungeons"
url = "/deep/"
weight = 6

[[menu.social]]
name = 'About'
url = "/about/"
weight = 100

[[menu.social]]
name = '<i class="fab fa-brands fa-github text-primary-emphasis" style="font-size:30px"></i>'
url = "https://github.com/Infiziert90/FFXIVGachaSpreadsheet"
weight = 101
