baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'FFXIV Gacha'

# Configure syntax highlight
[markup]
[markup.highlight]
style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html

[[module.mounts]]
source = "assets"
target = "assets"

SectionPagesMenu = "main"

[[menu.main]]
name = "FFXIV Gacha"
url = "/"
weight = 1

[[menu.main]]
name = "Containers"
weight = 2
identifier = "containers"

[[menu.main]]
parent = "containers"
name = "Coffers"
url = "/coffer/"
weight = 1

[[menu.main]]
parent = "containers"
name = "Lockboxes"
url = "/lockbox/"
weight = 2

[[menu.main]]
parent = "containers"
name = "Card Packs"
url = "/card/"
weight = 3

[[menu.main]]
parent = "containers"
name = "LogoFrag"
url = "/logofrag/"
weight = 4

[[menu.main]]
name = "Instance Drops"
weight = 3
identifier = "instances"

[[menu.main]]
parent = "instances"
name = "Deep Dungeons"
url = "/deep/"
weight = 1

[[menu.main]]
parent = "instances"
name = "Loot"
url = "/loot/"
weight = 2

[[menu.main]]
name = "Others"
weight = 4
identifier = "others"

[[menu.main]]
parent = "others"
name = "Eureka Bunnies"
url = "/bunny/"
weight = 1

[[menu.main]]
parent = "others"
name = "Desynthesis"
url = "/desynth/"
weight = 2

[[menu.main]]
parent = "others"
name = "Ventures"
url = "/venture/"
weight = 3

[[menu.social]]
name = 'About'
url = "/about/"
weight = 100

[[menu.social]]
name = '<i class="fab fa-brands fa-github text-primary-emphasis" style="font-size:30px"></i>'
url = "https://github.com/Infiziert90/FFXIVGachaSpreadsheet"
weight = 101
